export const countriesData = {
  "United States": {
    California: {
      "Los Angeles": {
        towns: [
          "Hollywood",
          "Beverly Hills",
          "Santa Monica",
          "Pasadena",
          "Glendale",
          "Burbank",
          "Culver City",
          "West Hollywood",
        ],
      },
      "San Francisco": {
        towns: [
          "Chinatown",
          "Mission District",
          "Castro District",
          "Haight-Ashbury",
          "North Beach",
          "SOMA",
          "Richmond",
          "Sunset District",
        ],
      },
      "San Diego": {
        towns: [
          "La Jolla",
          "Coronado",
          "Chula Vista",
          "Escondido",
          "Carlsbad",
          "Encinitas",
          "Del Mar",
          "Solana Beach",
        ],
      },
      Sacramento: {
        towns: [
          "Midtown",
          "Downtown",
          "East Sacramento",
          "Land Park",
          "Natomas",
          "Pocket",
          "South Sacramento",
          "North Sacramento",
        ],
      },
    },
    Texas: {
      Houston: {
        towns: [
          "Downtown",
          "Montrose",
          "River Oaks",
          "The Heights",
          "Midtown",
          "Museum District",
          "Galleria",
          "Energy Corridor",
        ],
      },
      Dallas: {
        towns: [
          "Deep Ellum",
          "Bishop Arts District",
          "Uptown",
          "Downtown",
          "Lakewood",
          "Oak Cliff",
          "Preston Hollow",
          "Park Cities",
        ],
      },
      Austin: {
        towns: [
          "South Austin",
          "East Austin",
          "West Lake Hills",
          "Zilker",
          "Hyde Park",
          "Clarksville",
          "Tarrytown",
          "Bouldin Creek",
        ],
      },
      "San Antonio": {
        towns: [
          "Southtown",
          "King William",
          "Alamo Heights",
          "Stone Oak",
          "The Majestic Square",
          "Monte Vista",
          "Brackenridge Park",
          "Medical Center",
        ],
      },
    },
    "New York": {
      "New York City": {
        towns: [
          "Manhattan",
          "Brooklyn",
          "Queens",
          "Bronx",
          "Staten Island",
          "Harlem",
          "Greenwich Village",
          "SoHo",
        ],
      },
      Buffalo: {
        towns: [
          "Elmwood Village",
          "Allentown",
          "Downtown",
          "North Buffalo",
          "South Buffalo",
          "West Side",
          "East Side",
          "Riverside",
        ],
      },
      Rochester: {
        towns: [
          "Park Avenue",
          "South Wedge",
          "Corn Hill",
          "Neighborhood of the Arts",
          "Upper Mount Hope",
          "19th Ward",
          "Swillburg",
          "Monroe Village",
        ],
      },
      Syracuse: {
        towns: [
          "University Hill",
          "Armory Square",
          "Eastwood",
          "Westcott",
          "Sedgwick",
          "Strathmore",
          "Hawley-Green",
          "Near Northeast",
        ],
      },
    },
    Florida: {
      Miami: {
        towns: [
          "South Beach",
          "Little Havana",
          "Coral Gables",
          "Coconut Grove",
          "Wynwood",
          "Design District",
          "Brickell",
          "Key Biscayne",
        ],
      },
      Orlando: {
        towns: [
          "Winter Park",
          "College Park",
          "Thornton Park",
          "Mills 50",
          "SODO",
          "Lake Nona",
          "Dr. Phillips",
          "Baldwin Park",
        ],
      },
      Tampa: {
        towns: [
          "Ybor City",
          "Hyde Park",
          "Westshore",
          "Downtown",
          "Seminole Heights",
          "South Tampa",
          "New Tampa",
          "Carrollwood",
        ],
      },
      Jacksonville: {
        towns: [
          "Riverside",
          "Avondale",
          "San Marco",
          "Springfield",
          "Five Points",
          "Murray Hill",
          "Mandarin",
          "Atlantic Beach",
        ],
      },
    },
  },
  India: {
    Maharashtra: {
      Mumbai: {
        towns: [
          "Bandra",
          "Andheri",
          "Juhu",
          "Powai",
          "Goregaon",
          "Malad",
          "Thane",
          "Navi Mumbai",
        ],
      },
      Pune: {
        towns: [
          "Koregaon Park",
          "Hinjewadi",
          "Baner",
          "Aundh",
          "Kothrud",
          "Warje",
          "Pimpri-Chinchwad",
          "Hadapsar",
        ],
      },
      Nagpur: {
        towns: [
          "Sadar",
          "Dharampeth",
          "Civil Lines",
          "Ramdaspeth",
          "Shankar Nagar",
          "Bajaj Nagar",
          "Pratap Nagar",
          "Hingna",
        ],
      },
      Nashik: {
        towns: [
          "College Road",
          "Gangapur Road",
          "Pathardi Phata",
          "Indira Nagar",
          "Panchavati",
          "Trimbak Road",
          "Canada Corner",
          "Ashok Stambh",
        ],
      },
    },
    Karnataka: {
      Bangalore: {
        towns: [
          "Koramangala",
          "Indiranagar",
          "Whitefield",
          "Electronic City",
          "Jayanagar",
          "Malleswaram",
          "HSR Layout",
          "BTM Layout",
        ],
      },
      Mysore: {
        towns: [
          "Saraswathipuram",
          "Vijayanagar",
          "Kuvempunagar",
          "Hebbal",
          "Jayalakshmipuram",
          "Gokulam",
          "Nazarbad",
          "Chamundipuram",
        ],
      },
      Hubli: {
        towns: [
          "Vidyanagar",
          "Keshwapur",
          "Unkal",
          "Gokul Road",
          "Kelgeri",
          "Toll Naka",
          "Deshpande Nagar",
          "Club Road",
        ],
      },
      Mangalore: {
        towns: [
          "Hampankatta",
          "Kadri",
          "Balmatta",
          "Kankanady",
          "Yeyyadi",
          "Surathkal",
          "Ullal",
          "Bondel",
        ],
      },
    },
    "Tamil Nadu": {
      Chennai: {
        towns: [
          "T. Nagar",
          "Anna Nagar",
          "Adyar",
          "Velachery",
          "Tambaram",
          "Porur",
          "OMR",
          "ECR",
        ],
      },
      Coimbatore: {
        towns: [
          "RS Puram",
          "Peelamedu",
          "Saibaba Colony",
          "Gandhipuram",
          "Race Course",
          "Singanallur",
          "Vadavalli",
          "Ukkadam",
        ],
      },
      Madurai: {
        towns: [
          "Anna Nagar",
          "K.K. Nagar",
          "Sellur",
          "Vilangudi",
          "Thiruparankundram",
          "Alagar Kovil",
          "Pasumalai",
          "Gomathipuram",
        ],
      },
      Salem: {
        towns: [
          "Five Roads",
          "Anna Nagar",
          "Suramangalam",
          "Fairlands",
          "Hasthampatti",
          "Ammapet",
          "Kondalampatti",
          "Shevapet",
        ],
      },
    },
    "Uttar Pradesh": {
      Lucknow: {
        towns: [
          "Hazratganj",
          "Gomti Nagar",
          "Indira Nagar",
          "Aliganj",
          "Mahanagar",
          "Jankipuram",
          "Alambagh",
          "Chinhat",
        ],
      },
      Kanpur: {
        towns: [
          "Civil Lines",
          "Mall Road",
          "Swaroop Nagar",
          "Govind Nagar",
          "Kidwai Nagar",
          "Kalyanpur",
          "Barra",
          "Kakadeo",
        ],
      },
      Agra: {
        towns: [
          "Sadar Bazaar",
          "Civil Lines",
          "Dayal Bagh",
          "Sikandra",
          "Fatehabad Road",
          "Kamla Nagar",
          "Loha Mandi",
          "Trans Yamuna",
        ],
      },
      Varanasi: {
        towns: [
          "Cantonment",
          "Godowlia",
          "Lanka",
          "Bhelupur",
          "Sigra",
          "Mahmoorganj",
          "Sarnath",
          "Ramnagar",
        ],
      },
    },
  },
  "United Kingdom": {
    England: {
      London: {
        towns: [
          "Westminster",
          "Camden",
          "Greenwich",
          "Kensington",
          "Chelsea",
          "Hackney",
          "Tower Hamlets",
          "Southwark",
        ],
      },
      Manchester: {
        towns: [
          "City Centre",
          "Northern Quarter",
          "Chorlton",
          "Didsbury",
          "Fallowfield",
          "Withington",
          "Rusholme",
          "Hulme",
        ],
      },
      Birmingham: {
        towns: [
          "City Centre",
          "Digbeth",
          "Jewellery Quarter",
          "Edgbaston",
          "Moseley",
          "Kings Heath",
          "Harborne",
          "Selly Oak",
        ],
      },
      Liverpool: {
        towns: [
          "City Centre",
          "Albert Dock",
          "Cavern Quarter",
          "Georgian Quarter",
          "Chinatown",
          "Ropewalks",
          "Baltic Triangle",
          "Toxteth",
        ],
      },
    },
    Scotland: {
      Edinburgh: {
        towns: [
          "Old Town",
          "New Town",
          "Leith",
          "Morningside",
          "Bruntsfield",
          "Stockbridge",
          "Portobello",
          "Corstorphine",
        ],
      },
      Glasgow: {
        towns: [
          "City Centre",
          "West End",
          "Merchant City",
          "Southside",
          "East End",
          "Finnieston",
          "Partick",
          "Shawlands",
        ],
      },
      Aberdeen: {
        towns: [
          "City Centre",
          "Old Aberdeen",
          "Rosemount",
          "Woodside",
          "Torry",
          "Ferryhill",
          "Kincorth",
          "Cove",
        ],
      },
      Dundee: {
        towns: [
          "City Centre",
          "West End",
          "Stobswell",
          "Hilltown",
          "Lochee",
          "Broughty Ferry",
          "Blackness",
          "Charleston",
        ],
      },
    },
    Wales: {
      Cardiff: {
        towns: [
          "City Centre",
          "Cardiff Bay",
          "Roath",
          "Canton",
          "Pontcanna",
          "Cathays",
          "Llandaff",
          "Whitchurch",
        ],
      },
      Swansea: {
        towns: [
          "City Centre",
          "Mumbles",
          "Uplands",
          "Sketty",
          "Gorseinon",
          "Pontarddulais",
          "Clydach",
          "Bishopston",
        ],
      },
      Newport: {
        towns: [
          "City Centre",
          "Maindee",
          "Pill",
          "Rogerstone",
          "Caerleon",
          "Langstone",
          "Bettws",
          "Alway",
        ],
      },
      Wrexham: {
        towns: [
          "Town Centre",
          "Rossett",
          "Marford",
          "Gresford",
          "Ruabon",
          "Rhostyllen",
          "Gwersyllt",
          "Bradley",
        ],
      },
    },
    "Northern Ireland": {
      Belfast: {
        towns: [
          "City Centre",
          "Titanic Quarter",
          "Stranmillis",
          "Malone",
          "Ballyhackamore",
          "Lisburn Road",
          "Botanic",
          "Cathedral Quarter",
        ],
      },
      Derry: {
        towns: [
          "City Side",
          "Waterside",
          "Bogside",
          "Creggan",
          "Shantallow",
          "Galliagh",
          "Rosemount",
          "Strand Road",
        ],
      },
      Lisburn: {
        towns: [
          "City Centre",
          "Hillhall",
          "Lambeg",
          "Dunmurry",
          "Derriaghy",
          "Seymour Hill",
          "Old Warren",
          "Ballyskeagh",
        ],
      },
      Newry: {
        towns: [
          "City Centre",
          "Ballyholland",
          "Damolly",
          "Carnagh",
          "Daisyhill",
          "Bessbrook",
          "Camlough",
          "Crossmaglen",
        ],
      },
    },
  },
  Canada: {
    Ontario: {
      Toronto: {
        towns: [
          "Downtown",
          "Yorkville",
          "The Beaches",
          "Leslieville",
          "Kensington Market",
          "Distillery District",
          "Queen West",
          "Liberty Village",
        ],
      },
      Ottawa: {
        towns: [
          "ByWard Market",
          "Glebe",
          "Westboro",
          "Hintonburg",
          "Sandy Hill",
          "New Edinburgh",
          "Old Ottawa South",
          "Alta Vista",
        ],
      },
      Hamilton: {
        towns: [
          "Downtown",
          "Westdale",
          "Locke Street",
          "James Street North",
          "Dundas",
          "Ancaster",
          "Stoney Creek",
          "Flamborough",
        ],
      },
      London: {
        towns: [
          "Downtown",
          "Old North",
          "Wortley Village",
          "Byron",
          "Masonville",
          "White Oaks",
          "Pond Mills",
          "Oakridge",
        ],
      },
    },
    Quebec: {
      Montreal: {
        towns: [
          "Old Montreal",
          "Plateau",
          "Mile End",
          "Outremont",
          "Westmount",
          "NDG",
          "Verdun",
          "Hochelaga",
        ],
      },
      "Quebec City": {
        towns: [
          "Old Quebec",
          "Saint-Roch",
          "Montcalm",
          "Sainte-Foy",
          "Charlesbourg",
          "Beauport",
          "Limoilou",
          "Cap-Rouge",
        ],
      },
      Laval: {
        towns: [
          "Chomedey",
          "Vimont",
          "Pont-Viau",
          "Duvernay",
          "Fabreville",
          "Sainte-Rose",
          "Auteuil",
          "Sainte-Dorothée",
        ],
      },
      Gatineau: {
        towns: [
          "Hull",
          "Aylmer",
          "Buckingham",
          "Masson-Angers",
          "Templeton",
          "Cantley",
          "Chelsea",
          "Val-des-Monts",
        ],
      },
    },
    "British Columbia": {
      Vancouver: {
        towns: [
          "Downtown",
          "Kitsilano",
          "Gastown",
          "Yaletown",
          "Commercial Drive",
          "Main Street",
          "West End",
          "Chinatown",
        ],
      },
      Victoria: {
        towns: [
          "Inner Harbour",
          "James Bay",
          "Fernwood",
          "Oak Bay",
          "Esquimalt",
          "Saanich",
          "View Royal",
          "Colwood",
        ],
      },
      Surrey: {
        towns: [
          "Newton",
          "Guildford",
          "Fleetwood",
          "Cloverdale",
          "South Surrey",
          "White Rock",
          "Whalley",
          "Fraser Heights",
        ],
      },
      Burnaby: {
        towns: [
          "Metrotown",
          "Brentwood",
          "Lougheed",
          "Edmonds",
          "Deer Lake",
          "Capitol Hill",
          "Sperling",
          "Heights",
        ],
      },
    },
    Alberta: {
      Calgary: {
        towns: [
          "Downtown",
          "Kensington",
          "Inglewood",
          "Mission",
          "Hillhurst",
          "Bridgeland",
          "Beltline",
          "Eau Claire",
        ],
      },
      Edmonton: {
        towns: [
          "Downtown",
          "Whyte Avenue",
          "Oliver",
          "Garneau",
          "Bonnie Doon",
          "Millwoods",
          "Jasper Place",
          "Beverly",
        ],
      },
      "Red Deer": {
        towns: [
          "Downtown",
          "Mountview",
          "Riverside Meadows",
          "Normandeau",
          "Anders",
          "Johnstone Crossing",
          "Oriole Park",
          "Highland Green",
        ],
      },
      Lethbridge: {
        towns: [
          "Downtown",
          "Henderson Lake",
          "Copperwood",
          "Southgate",
          "West Lethbridge",
          "Park Meadows",
          "Tudor Estates",
          "Mountain Heights",
        ],
      },
    },
  },
  Australia: {
    "New South Wales": {
      Sydney: {
        towns: [
          "CBD",
          "Bondi",
          "Manly",
          "Paddington",
          "Surry Hills",
          "Newtown",
          "Glebe",
          "Balmain",
        ],
      },
      Newcastle: {
        towns: [
          "City Centre",
          "The Hill",
          "Cooks Hill",
          "Carrington",
          "Wickham",
          "Hamilton",
          "Merewether",
          "Bar Beach",
        ],
      },
      Wollongong: {
        towns: [
          "City Centre",
          "North Wollongong",
          "Fairy Meadow",
          "Corrimal",
          "Thirroul",
          "Bulli",
          "Austinmer",
          "Helensburgh",
        ],
      },
      Parramatta: {
        towns: [
          "CBD",
          "Westmead",
          "Harris Park",
          "Granville",
          "Merrylands",
          "Holroyd",
          "Girraween",
          "Greystanes",
        ],
      },
    },
    Victoria: {
      Melbourne: {
        towns: [
          "CBD",
          "St Kilda",
          "Fitzroy",
          "Carlton",
          "Richmond",
          "South Yarra",
          "Prahran",
          "Brunswick",
        ],
      },
      Geelong: {
        towns: [
          "City Centre",
          "Newtown",
          "South Geelong",
          "East Geelong",
          "North Geelong",
          "Belmont",
          "Grovedale",
          "Highton",
        ],
      },
      Ballarat: {
        towns: [
          "City Centre",
          "Sebastopol",
          "Wendouree",
          "Lake Wendouree",
          "Delacombe",
          "Alfredton",
          "Bakery Hill",
          "Golden Point",
        ],
      },
      Bendigo: {
        towns: [
          "City Centre",
          "Golden Square",
          "Kangaroo Flat",
          "Eaglehawk",
          "Strathdale",
          "Epsom",
          "Kennington",
          "Flora Hill",
        ],
      },
    },
    Queensland: {
      Brisbane: {
        towns: [
          "CBD",
          "South Bank",
          "New Farm",
          "Fortitude Valley",
          "West End",
          "Paddington",
          "Teneriffe",
          "Kangaroo Point",
        ],
      },
      "Gold Coast": {
        towns: [
          "Surfers Paradise",
          "Broadbeach",
          "Burleigh Heads",
          "Coolangatta",
          "Southport",
          "Main Beach",
          "Mermaid Beach",
          "Palm Beach",
        ],
      },
      Cairns: {
        towns: [
          "City Centre",
          "Cairns North",
          "Edge Hill",
          "Whitfield",
          "Redlynch",
          "Smithfield",
          "Trinity Beach",
          "Palm Cove",
        ],
      },
      Townsville: {
        towns: [
          "City Centre",
          "South Townsville",
          "North Ward",
          "Belgian Gardens",
          "Hyde Park",
          "Aitkenvale",
          "Douglas",
          "Annandale",
        ],
      },
    },
    "Western Australia": {
      Perth: {
        towns: [
          "CBD",
          "Fremantle",
          "Subiaco",
          "Northbridge",
          "Leederville",
          "Mount Lawley",
          "South Perth",
          "Cottesloe",
        ],
      },
      Mandurah: {
        towns: [
          "City Centre",
          "Halls Head",
          "Greenfields",
          "Meadow Springs",
          "Falcon",
          "Dawesville",
          "Erskine",
          "Wannanup",
        ],
      },
      Bunbury: {
        towns: [
          "City Centre",
          "South Bunbury",
          "East Bunbury",
          "Withers",
          "Carey Park",
          "College Grove",
          "Glen Iris",
          "Australind",
        ],
      },
      Rockingham: {
        towns: [
          "City Centre",
          "Safety Bay",
          "Shoalwater",
          "Warnbro",
          "Port Kennedy",
          "Secret Harbour",
          "Golden Bay",
          "Singleton",
        ],
      },
    },
  },
  Germany: {
    Bavaria: {
      Munich: {
        towns: [
          "Altstadt",
          "Schwabing",
          "Maxvorstadt",
          "Lehel",
          "Haidhausen",
          "Au",
          "Giesing",
          "Sendling",
        ],
      },
      Nuremberg: {
        towns: [
          "Altstadt",
          "Sebald",
          "Lorenz",
          "Gostenhof",
          "St. Johannis",
          "Wöhrd",
          "Gleißhammer",
          "Langwasser",
        ],
      },
      Augsburg: {
        towns: [
          "Innenstadt",
          "Antonsviertel",
          "Bärenkeller",
          "Pfersee",
          "Oberhausen",
          "Lechhausen",
          "Hochfeld",
          "Göggingen",
        ],
      },
      Regensburg: {
        towns: [
          "Altstadt",
          "Stadtamhof",
          "Steinweg",
          "Ostenviertel",
          "Weichs",
          "Kasernenviertel",
          "Konradsiedlung",
          "Burgweinting",
        ],
      },
    },
    "North Rhine-Westphalia": {
      Cologne: {
        towns: [
          "Altstadt-Nord",
          "Altstadt-Süd",
          "Neustadt-Nord",
          "Neustadt-Süd",
          "Deutz",
          "Nippes",
          "Ehrenfeld",
          "Lindenthal",
        ],
      },
      Düsseldorf: {
        towns: [
          "Altstadt",
          "Stadtmitte",
          "Pempelfort",
          "Derendorf",
          "Golzheim",
          "Oberkassel",
          "Lörick",
          "Heerdt",
        ],
      },
      Dortmund: {
        towns: [
          "Innenstadt-Nord",
          "Innenstadt-Ost",
          "Innenstadt-West",
          "Eving",
          "Scharnhorst",
          "Brackel",
          "Aplerbeck",
          "Hörde",
        ],
      },
      Essen: {
        towns: [
          "Stadtmitte",
          "Frohnhausen",
          "Altendorf",
          "Holsterhausen",
          "Rüttenscheid",
          "Bergerhausen",
          "Rellinghausen",
          "Werden",
        ],
      },
    },
    "Baden-Württemberg": {
      Stuttgart: {
        towns: [
          "Mitte",
          "Nord",
          "Ost",
          "Süd",
          "West",
          "Bad Cannstatt",
          "Feuerbach",
          "Zuffenhausen",
        ],
      },
      Mannheim: {
        towns: [
          "Innenstadt",
          "Jungbusch",
          "Neckarstadt-Ost",
          "Neckarstadt-West",
          "Schwetzingerstadt",
          "Oststadt",
          "Lindenhof",
          "Neckarau",
        ],
      },
      Karlsruhe: {
        towns: [
          "Innenstadt-Ost",
          "Innenstadt-West",
          "Südstadt",
          "Südweststadt",
          "Weststadt",
          "Nordstadt",
          "Oststadt",
          "Mühlburg",
        ],
      },
      Freiburg: {
        towns: [
          "Altstadt",
          "Neuburg",
          "Herdern",
          "Zähringen",
          "Brühl",
          "Hochdorf",
          "Littenweiler",
          "Günterstal",
        ],
      },
    },
    Hamburg: {
      Hamburg: {
        towns: [
          "Altstadt",
          "Neustadt",
          "St. Pauli",
          "St. Georg",
          "Eimsbüttel",
          "Altona",
          "Harburg",
          "Bergedorf",
        ],
      },
    },
  },
};
